spring:
   profiles: 
      active: 
      - d
---
spring:
   profiles: dev
   application: 
      name: microservicecloud-config-wy-dev
---
spring:
   profiles: test
   application: 
      name: microservicecloud-config-wy-test
