spring: 
	profiles: 
	  active:
		-dev
---
spring: 
	profile: dev #开发环境
	application: 
		name: microservicecloud-config-wy-dev
---
spring: 
	profile: test #测试环境
	application: 
		name: microservicecloud-config-wy-test
# 请保持为UTF-8格式